- link:
    "C:/laragon/usr/sites.conf": laragon/sites.conf
    "C:/laragon/usr/laragon.ini": laragon/laragon.ini
    "C:/laragon/usr/packages.conf": laragon/packages.conf
    "C:/laragon/usr/tpl/VirtualHost.SSL.manifest.tpl": laragon/tpl/VirtualHost.SSL.manifest.tpl

- shell:
  - [bash ./bin/ack-install, Installing ack tool]
  - [bash ./bin/wp-cli-install, Installing WP-CLI]
  - [bash ./bin/laragon-system, Creating Own Laragon Environment]
