- clean: ['~']

- link:
    ~/.gitconfig: git/gitconfig
    ~/.gitignore_global: git/gitignore_global
    ~/.bash_profile: bash/bash_profile
    ~/.minttyrc: mintty/minttyrc
    ~/.bashrc: bash/bashrc
    ~/.npmrc: npm/npmrc
    ~/.vim: vim/vim
    ~/.vimrc: vim/vimrc
    ~/.zsh: zsh/zsh
    ~/.zshrc: zsh/zshrc
    ~/.wp: wp

- shell:
  - vim +PluginInstall +qall
